pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'thanhkon241203265' // ten docker desktop của ban
        DOCKERHUB_PASS = credentials('dockerhub-credentials-deploy') // id credential
        IMAGE_NAME = 'thanhkon241203265/docker-deploy' // ten image

        K8S_DEPLOYMENT_NAME = 'springboot-app'
        K8S_NAMESPACE = 'default'
    }
    tools {
        maven 'MAVEN_HOME'
        jdk 'JDK17'
    }
    stages {
        stage('Checkout') {
            steps {
                echo '📦 Cloning GitHub repository...'
                git branch: 'main', url: 'https://github.com/thanh241203/demo-with-kurbenet.git'
            }
        }
        stage('Build') {
            steps {
                echo '🔨 Building the project...'
                dir('demo') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('demo') {
                    script {
                        def imageTag = "v${env.BUILD_NUMBER}"
                        bat "docker build -t ${IMAGE_NAME}:${imageTag} ."
                        bat "docker tag ${IMAGE_NAME}:${imageTag} ${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials-deploy', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        def imageTag = "v${env.BUILD_NUMBER}"
                        bat """
                    echo Logging in to DockerHub...
                    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    docker push ${IMAGE_NAME}:${imageTag}
                    docker push ${IMAGE_NAME}:latest
                """
                    }
                }
            }
        }

        stage('Test') {
            steps {
                // Run Maven tests
                dir('demo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo '🚀 Deploying image to Kubernetes cluster...'

                withCredentials([file(credentialsId: 'kurbenet-config', variable: 'KUBECONFIG_FILE')]) {
                    script {
                        env.KUBECONFIG = KUBECONFIG_FILE
                        def imageTag = "v${env.BUILD_NUMBER}"
                        def fullImage = "${IMAGE_NAME}:${imageTag}"

                        // 🔍 Hiển thị context hiện tại
                        bat 'kubectl config current-context'
                        echo 'kubectl config current-context'

                        // 🧠 Áp dụng service và deployment
                        bat "minikube kubectl -- apply -f ${WORKSPACE}/demo/service.yaml -n ${env.K8S_NAMESPACE} --validate=false"
                        bat "minikube kubectl -- apply -f ${WORKSPACE}/demo/deployment.yaml -n ${env.K8S_NAMESPACE} --validate=false"

                        echo '📋 Checking current resources...'
                        bat 'minikube kubectl -- get pods -n default'
                        bat 'minikube kubectl -- get svc -n default'
                        // 🔄 Cập nhật image mới cho Deployment
                        bat "minikube kubectl -- set image deployment/springboot-deploy springboot=${fullImage} -n ${env.K8S_NAMESPACE}"


                        // ⏳ Chờ rollout hoàn tất
                        bat "minikube kubectl rollout status deployment/${env.K8S_DEPLOYMENT_NAME} -n ${env.K8S_NAMESPACE}"
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline finibated successfully! Image built and deployed.'
        }
    }
}
