pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'thanhkon241203265'
        DOCKERHUB_PASS = credentials('dockerhub-credentials-deploy')
        IMAGE_NAME = 'thanhkon241203265/docker-deploy'
    }
    tools {
        maven 'MAVEN_HOME'
        jdk 'JDK17'
    }
    stages {
        stage('Checkout') {
            steps {
                echo '📦 Cloning GitHub repository...'
                git branch: 'main', url: 'https://github.com/thanh241203/demo-with-kurbenet.git'
            }
        }
        stage('Build') {
            steps {
                echo '🔨 Building the project...'
                dir('demo') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('demo') {
                    script {
                        def imageTag = "v${env.BUILD_NUMBER}"
                        bat "docker build -t ${IMAGE_NAME}:${imageTag} ."
                        bat "docker tag ${IMAGE_NAME}:${imageTag} ${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials-deploy', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        def imageTag = "v${env.BUILD_NUMBER}"
                        bat """
                    echo Logging in to DockerHub...
                    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    docker push ${IMAGE_NAME}:${imageTag}
                    docker push ${IMAGE_NAME}:latest
                """
                    }
                }
            }
        }
        stage('Test') {
            steps {
                // Run Maven tests
                dir('demo') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline finibated successfully! Image built and deployed.'
        }
    }
}
