pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo '📦 Cloning GitHub repository...'
                git branch: 'main', url: 'https://github.com/thanh241203/demo-with-kurbenet.git'
            }
        }
        stage('Build') {
            steps {
                // Run Maven build
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                // Run Maven tests
                bat 'mvn test'
            }
        }
        stage('Package') {
            steps {
                // Package the application (optional)
                bat 'mvn package'
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline finibated successfully! Image built and deployed.'
        }
    }
}
